package com.yee.authority.vo;

import java.util.Date;

public class LoginHist {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_HIST.ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_HIST.LOGIN_ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_HIST.LOGIN_SUCCESS
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    private String loginSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGIN_HIST.LOGIN_TIME
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_HIST.ID
     *
     * @return the value of LOGIN_HIST.ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    
    private String active;
    
    
    public String getActive() {
		return active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_HIST.ID
     *
     * @param id the value for LOGIN_HIST.ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_HIST.LOGIN_ID
     *
     * @return the value of LOGIN_HIST.LOGIN_ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_HIST.LOGIN_ID
     *
     * @param loginId the value for LOGIN_HIST.LOGIN_ID
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == null ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_HIST.LOGIN_SUCCESS
     *
     * @return the value of LOGIN_HIST.LOGIN_SUCCESS
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public String getLoginSuccess() {
        return loginSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_HIST.LOGIN_SUCCESS
     *
     * @param loginSuccess the value for LOGIN_HIST.LOGIN_SUCCESS
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public void setLoginSuccess(String loginSuccess) {
        this.loginSuccess = loginSuccess == null ? null : loginSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGIN_HIST.LOGIN_TIME
     *
     * @return the value of LOGIN_HIST.LOGIN_TIME
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGIN_HIST.LOGIN_TIME
     *
     * @param loginTime the value for LOGIN_HIST.LOGIN_TIME
     *
     * @mbggenerated Tue Jul 07 16:21:00 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}
